python_study/python_study/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from study_admin.views import *
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include('study_admin.urls', namespace='admin')),
    url(r'^login/$', Login.as_view(), name='login'),
    url(r'^join/$', Join.as_view(), name='join'),
    url(r'^logout/$', Logout.as_view(), name='logout'),
    url(r'^', include('study_user.urls', namespace='user')),
    #url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

python_study/study_user/urls.py
from django.conf.urls import url
from study_user.views import *

urlpatterns = [
    url(r'^$', RedirectFirstArticle.as_view(), name='redirect_first_article'),
    url(r'^(?P<article_id>\w+)/$', ArticleView.as_view(), name='article_view'),
]

python_study/templates/user/view.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, user-scalable=no" />
    <title>Python Web Study</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/sandstone/bootstrap.min.css" rel="stylesheet" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <link href="{% static 'css/general.css' %}" rel="stylesheet" />
    <link href="{% static 'css/article_view.css' %}" rel="stylesheet" />
    <link href="{% static 'css/shCoreDefault.css' %}" rel="stylesheet" />
    <link href="{% static 'css/shThemeDefault.css' %}" rel="stylesheet" />
    {% block addition_css %}
    {% endblock %}
</head>
<body>
    <a id="logout-btn" href="{% url 'logout' %}" class="btn btn-primary btn-sm"><i class="fa fa-sign-out" aria-hidden="true"></i> 로그아웃</a>
    <div class="row">
        <div id="chapter" class="col-md-2 col-sm-3 col-xs-12">
            <div class="list-group">
                {% for article in article_list %}
                    <a href="{% url 'user:article_view' article_id=article.id %}" class="list-group-item">{{ article.chapter }} {{ article.title }}</a>
                {% endfor %}
            </div>
        </div>
        <div id="content" class="col-md-10 col-sm-9 col-xs-12">
            <div class="page-header">
                <h1>{{ article.chapter }} {{ article.title }}</h1>
            </div>
            {{ article.content|safe }}
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <script src="{% static 'js/shCore.js' %}"></script>
    <script src="{% static 'js/shLegacy.js' %}"></script>
    <script src="{% static 'js/shBrushBash.js' %}"></script>
    <script src="{% static 'js/shBrushCpp.js' %}"></script>
    <script src="{% static 'js/shBrushCss.js' %}"></script>
    <script src="{% static 'js/shBrushDiff.js' %}"></script>
    <script src="{% static 'js/shBrushJScript.js' %}"></script>
    <script src="{% static 'js/shBrushPhp.js' %}"></script>
    <script src="{% static 'js/shBrushPlain.js' %}"></script>
    <script src="{% static 'js/shBrushPython.js' %}"></script>
    <script src="{% static 'js/shBrushSql.js' %}"></script>
    <script src="{% static 'js/shBrushXml.js' %}"></script>
    <script type="text/javascript">
        SyntaxHighlighter.all();
    </script>
    {% block addition_js %}
    {% endblock %}
</body>
</html>